# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15e6YLEZWzeOrDiIaUj_j4xw603o0ZHxz
"""

l = [2,3,4]

import array
ar = array.array('i',[1,2,3,4])

ar

ar[0]

ar[1:2]

ar[1] = 3

ar

import numpy as np
ar = np.array([1,2,3,4])

ar

type(ar)

ar1 = np.array([[1,2,3],[4,5,6]])

ar1

l = [ [2,3],[4,5],[6,7],[7,8] ]

ar2 = np.array(l)

ar2.shape

ar.shape

ar1.shape

ar.ndim

ar1.ndim

ar2.ndim

ar3 = np.array([[[1,2,3,4],[5,6,7,8]], [[3,4,5],[7,6,5]]])

np.zeros(3)

np.zeros((2,2))

np.ones((2,2))

r = np.random.rand(2,2)

np.random.normal((2,3))

r.dtype

# int, float, string, bool
# int8 (-128 to 127)
# int16
# int32
# int64 

# float16
# float32

s = np.array(['a','b','c'])

s

ar = np.array([23,34,45], dtype='float16')

ar

ar.dtype

ar = np.array([[1,2,3],[4,5,6]])

ar

l = [[1, 2, 3],
       [4, 5, 6]]

l[0]

l[0][1]

ar[0]

ar[0][1]

ar[0,1]

ar

ar[:,0]

#@title Default title text
ar[:,1]

ar[0,:]

ar[:,:2]

ar[:,[0,2]]

ar = np.array([[1,2,3],[4,5,6]])
ar1 = np.array([[4,5,6],[8,5,2]])

ar + ar1

ar - ar1

ar * ar1

ar / ar1

ar

sum(ar)

np.sum(ar)

np.min(ar)

np.max(ar)

ar.dot(ar1)

ar_copy = ar.copy()

# reshape of arrays

# range()
ar = np.arange(1,10)

ar

ar.shape

arr = ar.reshape(3,3)

arr

arr = np.array([1,2,3])
arr1 = np.array([10,11,12])

np.concatenate([arr,arr1])

arr = ar.reshape(3,3)

arr

arr1

np.vstack([arr, arr1])

np.hstack([arr,arr1])

np.array([[1,2,3],['a','b','c']])

"""# Pandas"""

import pandas as pd

s = pd.Series([1,2,3,4])

s

s[0]

s[0:3]

s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])

s1

s1['a']

s1[0]

s2 = pd.Series([1,2,3,4], index=[1,2,3,4])

s2

s2[1]

s2[0:3]

s2.loc[1]

s2.loc[1:3]

s2.iloc[1]

s2.iloc[1:3]

np.sum(s2)

s1 = pd.Series([1,2,3])
s2 = pd.Series([3,4,5])

s1 + s2

s1 - s2

s1_copy = s1.copy()

s1.describe()

s1.dtypes

pd.Series([1,2,3,'a'])

s1.values

# numpy arrays
# pandas series
# pandas dataframes

