# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBzlX5pYIA7eSTvJGgneMHbW2_0m1JFm
"""

import array
array.array('i', [2,3,4,5])

ar = array.array('i', [2,3,4,5])
ar[0]

type(ar[0])

type(ar[1:3])

ar[1:3]

import numpy as np

np.array([1,2,3])

np.array([[1,2,3], [4,5,6]])

ar = np.array([[1,2,3], [4,5,6]])

ar[0,0]

ar[:,[0,1]]

np.sum(ar)

np.abs(ar)

import pandas as pd

pd.Series([2,3,4])

pd.Series([2,3,4], index=['a','b','c'])

s = pd.Series([2,3,4], index=[1,2,3])

s[1]

s[1:3]

s.loc[1]

s.loc[1:3]

s.iloc[0]

"""#### Type conversion"""

import pandas as pd
category = pd.Series(['Fashoin', 'Food', 'Footware', 'Electronics'])
sales = pd.Series(['2345','45764','5646', '3445'])
date = pd.Series(['12/01/2021','12/01/2021','12/01/2021','12/01/2021'])

category

category.astype('category')

category = category.astype('category')

sales

sales = sales.astype('int')

sales

date

date = pd.to_datetime(date, format='%d/%m/%Y')

date

pd.Series({'Fashion':2345, 'Food':2335, 'Footware':5456, 'Electronics':4673})

ser = pd.Series({'Fashion':2345, 'Food':2335, 'Footware':5456, 'Electronics':4673})

ser.index

ser.values

ser['Fashion']

ser[0]

ser.loc['Fashion']

ser.iloc[0]

"""### Dataframe"""

import pandas as pd

pd.DataFrame({'Category':category, 'Sales':sales, 'Date':date})

data = pd.DataFrame({'Category':category, 'Sales':sales, 'Date':date})

data

data.dtypes

data.describe()

data.head()

data.tail()

data['Category']

type(data)

type(data['Sales'])

type(data.values)

data.values

data

"""## Slicing dataframes"""

data[['Category', 'Sales']]

data.loc[:,['Category','Sales']]

data.iloc[:,[0,1]]

data.loc[0:3,:]

data.iloc[0:3,:]

data.loc[0:3,['Category','Sales']]

data.iloc[0:3,0:2]

data.iloc[0:3,[0,1]]

data

data.loc[2,'Sales']

data.loc[2,'Sales'] = 5764

data

data[data['Sales'] > 5000]

data.loc[data['Sales'] > 500,:]

data.iloc[[False, True, True, False],:]

data.iloc[data['Sales'] > 5000,:]

data['Sales'] > 5000

(data['Sales'] > 5000).values

data.iloc[[False, True, True, False],:]

data.iloc[(data['Sales'] > 5000).values,:]

data.loc[pd.Series([True,False,True,False]), 'Category']

data.iloc[pd.Series([True,False,True,False]), 0]

data.loc[data['Sales'] > 5000, 'Category']

data['Sales'] > 5000

"""#### inserting data to dataframes"""

data

row = {'Category':'Luxury', 'Sales':3456, 'Date':'12/01/2021'}

data.append(row, ignore_index=True)

data.dtypes

row1 = {'Category':['Luxury'], 'Sales':[3456], 'Date':['12/01/2021']}

row_data1 = pd.DataFrame(row1)

row2 = {'Category':'Luxury', 'Sales':3456, 'Date':'12/01/2021'}

row_data2 = pd.DataFrame(row2, index=[4])

row_data2

row_data1

data.append(row_data1)

data.append(row_data2)

# dataframes -> slice -> insert data -> UPDATE DATA

"""#### Update data"""

whos

who

data

data.loc[1,'Sales']

data.loc[1,'Sales'] = 5764

data

data.iloc[2,1]

data.iloc[2,1] = 5567

data

data.loc[data['Category'] == 'Fashoin','Sales']

data.loc[data['Category'] == 'Fashoin','Sales'] = 3456

data

data['Location'] = 'Bangalore'

data

data['Distributor Location'] = ['Bangalore', 'Hyderabad', 'Mumbai', 'Chennai']

data

data1 = data[['Category', 'Sales', 'Date', 'Distributor Location']].copy()

data1

data2 = data.drop(columns=['Location'])

data

data2

data3 = data.iloc[:3,:]



data3

del data3['Location']

data3

# dataframes -> slicing -> insert -> update -> delete